# Use C++test 2022.0
name: CI-Test-2022-1

on:
  push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master,child_02 ]
  #workflow_dispatch:

permissions: write-all

jobs:
  test-cpptest:
    name: Analyze project with C/C++test
    runs-on: develop_work

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: ls_check2
      run: |
         pwd
         ls 

    - name: Generate BDF
      env: 
        CPPTEST_SCAN_OUTPUT_FILE: /home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker/DevelopSampleProject/BugDetective/cpptestscan.bdf
        CPPTEST_SCAN_PROJECT_NAME: DevelopSampleProject
      run: |
           cd /home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker/DevelopSampleProject
           #docker exec gcc /opt/app/parasoft/cpptest/bin/cpptesttrace make all
           docker exec gcc /home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker/DevelopSampleProject/generate_bdf.sh
      working-directory: /home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker/DevelopSampleProject
      
    - name: ls_check2
      run: |
         pwd
         cd /home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker
         mkdir -m 777 reports
         ls    
    - name: ls_check3
      run: |
         ls
         docker exec gcc gcc --version
         
    - name: change_permission
      run: |
         cd /home/keio/cpptest_git/cpptest_docker/sagyou/reports
         rm -rf report.sarif
         rm -rf report.xml

    - name: Run C++test_git
      # Use the 'run-cpptest-action' GitHub Action.
      uses: parasoft/run-cpptest-action@2.0.0
      with:
        installDir: '/opt/app/parasoft/cpptest/'
        compilerConfig: 'gcc_7-64'
        testConfig: 'builtin://Recommended Rules'
        reportFormat: xml,html,sarif
        input: '/home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker/DevelopSampleProject/BugDetective/cpptestscan.bdf'
        reportDir: '/home/keio/cpptest_git/cpptest_docker/sagyou/reports'
        additionalParams: '/home/keio/actions-runner/develop_runner/cpptest_docker/cpptest_docker/DevelopSampleProject/cpptestcli.properties'
        commandLinePattern: docker exec gcc "${installDir}/cpptestcli" -data "/home/keio/cpptest_git/cpptest_docker/sagyou/workdir" -config "${testConfig}" -bdf "${input}" -localsettings "${additionalParams}" -report "${reportDir}"
        

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      env: 
        GITHUB_TOKEN: ${{ secrets.MEHISYA }}
      with:
        sarif_file: /home/keio/cpptest_git/cpptest_docker/sagyou/reports/report.sarif
    
    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Static analysis reports
        path: reports/*.*
